# Generated by Django 3.1 on 2021-07-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20210618_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='astronomical_scientific_category',
        ),
        migrations.AddField(
            model_name='activity',
            name='astronomical_categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'group': 'astronomical_categories'}, related_name='_activity_astronomical_categories_+', to='activities.MetadataOption', verbose_name='Astronomical Scientific Categories'),
        ),
        migrations.AlterField(
            model_name='metadataoption',
            name='group',
            field=models.CharField(choices=[('age', 'Age'), ('level', 'Level'), ('time', 'Time'), ('group', 'Group'), ('supervised', 'Supervised'), ('cost', 'Cost per student'), ('location', 'Location'), ('skills', 'Core skills'), ('learning', 'Type(s) of learning activity'), ('astronomical_categories', 'Astronomy Categories'), ('earth_science_keyword', 'Earth Science keywords'), ('space_science_keyword', 'Space Science keywords')], max_length=50),
        ),
    ]
